
service: probot-esphome

frameworkVersion: "2"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  timeout: 10
  memorySize: 192
  environment:
    APP_ID: ${env:APP_ID}
    PRIVATE_KEY: ${env:PRIVATE_KEY}
    WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
    NODE_ENV: production
    LOG_LEVEL: debug

functions:
  webhooks:
    handler: ./lib/handler.webhooks
    exclude:
      - .devcontainer/**
    events:
      - httpApi:
          path: /api/github/webhooks
          method: post
